// GENERATED FILE. Do not edit.
// Source of truth: skyward-seo-pipeline/checks/seo.yaml
// Regenerate: python3 checks/tools/generate.py
// Edits made here are destroyed by the next run. To change a check, change the
// registry. From Phase 4 you will be able to propose a change at checks.goskyward.io.
//
// wqa-checks.ts holds the predicates, the code that decides whether a row
// fails a check. This file holds the numbers and the catalog those predicates
// read. The split is deliberate: the half that must never drift from the SOP is
// generated, and the half that needs a human is not.

// ─── thresholds ────────────────────────────────────────────────────────────
/** registry `title_max_chars`, used by C11, C17 */
export const TITLE_MAX_CHARS = 60;
/** registry `title_min_chars`, used by C18 */
export const TITLE_MIN_CHARS = 30;
/** registry `meta_min_chars`, used by C16, C21 */
export const META_MIN_CHARS = 100;
/** registry `meta_max_chars`, used by C15, C21 */
export const META_MAX_CHARS = 160;

export type GeneratedCheckCategory = "T" | "C" | "S";
export type GeneratedCheckKind = "active" | "blocked";
export type GeneratedKwDependency =
  | "Fix Now"
  | "Fix Now, Revisit"
  | "Phase 3 Dependent";

export type GeneratedCheckDef = {
  id: string;
  category: GeneratedCheckCategory;
  /** Short label for the UI. Carries the live threshold where there is one. */
  name: string;
  /** The check's name in the SOP, without the threshold hint. */
  sopName: string;
  action: string;
  kind: GeneratedCheckKind;
  blockedReason: string | null;
  kwDependency: GeneratedKwDependency;
  priority: string;
};

export const GENERATED_CHECKS: GeneratedCheckDef[] = [
  {
    id: "T1",
    category: "T",
    name: "Schema errors",
    sopName: "Schema errors",
    action: "Fix Schema",
    kind: "blocked",
    blockedReason: "Requires SF structured data report (contains_structured_data + validation_errors)",
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T2",
    category: "T",
    name: "Missing schema",
    sopName: "Missing schema",
    action: "Fix Schema (add)",
    kind: "blocked",
    blockedReason: "Requires SF structured data report",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T3",
    category: "T",
    name: "Review star opportunity",
    sopName: "Review star opportunity",
    action: "Fix Schema (add)",
    kind: "blocked",
    blockedReason: "Requires SF structured data report to confirm absence",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T4",
    category: "T",
    name: "Orphan with value",
    sopName: "Orphan with value",
    action: "Add Internal Links",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T5",
    category: "T",
    name: "Under-linked",
    sopName: "Under-linked",
    action: "Add Internal Links",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T6",
    category: "T",
    name: "Buried page (depth>=4)",
    sopName: "Buried page",
    action: "Improve Architecture",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T7",
    category: "T",
    name: "Over-linked underperformer",
    sopName: "Over-linked underperformer",
    action: "Remove Internal Links",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "T8",
    category: "T",
    name: "Indexable but not indexed",
    sopName: "Indexable but not indexed",
    action: "Fix Indexation",
    kind: "blocked",
    blockedReason: "Requires SF + GSC URL Inspection integration (indexed-in-Google column)",
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T9",
    category: "T",
    name: "Noindex on valuable page",
    sopName: "Noindex on valuable page",
    action: "Fix Indexation",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T10",
    category: "T",
    name: "Multiple canonicals",
    sopName: "Multiple canonicals",
    action: "Fix Multiple Canonicals",
    kind: "blocked",
    blockedReason: "Requires SF canonical-tags multi-value field",
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T11",
    category: "T",
    name: "Canonical mismatch",
    sopName: "Canonical mismatch",
    action: "Canonicalize",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T12",
    category: "T",
    name: "Not in sitemap",
    sopName: "Not in sitemap",
    action: "Add to Sitemap",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T13",
    category: "T",
    name: "Blocked resources (JS/CSS)",
    sopName: "Blocked resources",
    action: "Fix Blocked Resources",
    kind: "blocked",
    blockedReason: "Requires robots.txt + SF resources report",
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T14",
    category: "T",
    name: "JS rendering required",
    sopName: "JS rendering",
    action: "Verify JS Rendering",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "T15",
    category: "T",
    name: "No issues found",
    sopName: "None",
    action: "Leave As Is",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "T16",
    category: "T",
    name: "Pages linking to broken pages",
    sopName: "Pages linking to broken pages",
    action: "Update Internal Links",
    kind: "blocked",
    blockedReason: "Requires SF inlinks export to broken-URL set",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T17",
    category: "T",
    name: "HTTPS page linking to HTTP",
    sopName: "HTTPS linking to HTTP resources",
    action: "Fix Internal Links",
    kind: "blocked",
    blockedReason: "Requires SF inlinks raw URL inspection",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "T18",
    category: "T",
    name: "Missing social tags (OG/Twitter)",
    sopName: "Social tags",
    action: "Add Social Tags",
    kind: "blocked",
    blockedReason: "Requires SF social-tags extract",
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "T19",
    category: "T",
    name: "IndexNow candidates",
    sopName: "IndexNow candidates",
    action: "Submit to IndexNow",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "T20",
    category: "T",
    name: "Duplicate without canonical",
    sopName: "Duplicate without canonical",
    action: "Add Canonical",
    kind: "blocked",
    blockedReason: "Requires SF duplicate content report",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "C1",
    category: "C",
    name: "Revenue page losing traffic",
    sopName: "Revenue page losing traffic",
    action: "Refresh (URGENT)",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "C2",
    category: "C",
    name: "Low engagement (sessions>50, dur<30s)",
    sopName: "Low engagement",
    action: "Rewrite",
    kind: "active",
    blockedReason: null,
    kwDependency: "Phase 3 Dependent",
    priority: "P2",
  },
  {
    id: "C3",
    category: "C",
    name: "Cannibalization (2+ pages same KW)",
    sopName: "Cannibalization",
    action: "Merge (weaker to stronger)",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "C4",
    category: "C",
    name: "Thin content screen (<300 words, <10 sessions)",
    sopName: "Thin content",
    action: "Review; Rewrite only if it adds nothing original",
    kind: "active",
    blockedReason: null,
    kwDependency: "Phase 3 Dependent",
    priority: "P2",
  },
  {
    id: "C5",
    category: "C",
    name: "Losing traffic (negative session %)",
    sopName: "Losing traffic",
    action: "Refresh or Rewrite",
    kind: "active",
    blockedReason: null,
    kwDependency: "Phase 3 Dependent",
    priority: "P1",
  },
  {
    id: "C6",
    category: "C",
    name: "Ranking 3-10, SV>50",
    sopName: "Ranking 3-10",
    action: "Target w/ Links or Add Internal Links",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "C7",
    category: "C",
    name: "Ranking 11-20, SV>50",
    sopName: "Ranking 11-20",
    action: "Refresh or Rewrite",
    kind: "active",
    blockedReason: null,
    kwDependency: "Phase 3 Dependent",
    priority: "P2",
  },
  {
    id: "C8",
    category: "C",
    name: "Missing meta description",
    sopName: "Missing meta description",
    action: "Update Meta Description",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C9",
    category: "C",
    name: "Duplicate meta description",
    sopName: "Duplicate meta description",
    action: "Update Meta Description",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C10",
    category: "C",
    name: "Duplicate title",
    sopName: "Duplicate title",
    action: "Update Page Title",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C11",
    category: "C",
    name: "Title issues (length/stuffing)",
    sopName: "Title issues",
    action: "Update Page Title",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P1",
  },
  {
    id: "C12",
    category: "C",
    name: "Has refs but not ranking (rank>20)",
    sopName: "Has refs but not ranking",
    action: "Target w/ Links + Refresh",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "C13",
    category: "C",
    name: "Performing well (sess>50, words>1000)",
    sopName: "Performing well",
    action: "Leave As Is",
    kind: "active",
    blockedReason: null,
    kwDependency: "Phase 3 Dependent",
    priority: "P3",
  },
  {
    id: "C14",
    category: "C",
    name: "No issues found",
    sopName: "None",
    action: "Leave As Is",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "C15",
    category: "C",
    name: "Meta description too long (>160)",
    sopName: "Meta description too long",
    action: "Shorten Meta Description",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C16",
    category: "C",
    name: "Meta description too short (<100)",
    sopName: "Meta description too short",
    action: "Expand Meta Description",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C17",
    category: "C",
    name: "Title too long (>60)",
    sopName: "Title too long",
    action: "Shorten Title",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P1",
  },
  {
    id: "C18",
    category: "C",
    name: "Title too short (<30)",
    sopName: "Title too short",
    action: "Expand Title",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now, Revisit",
    priority: "P3",
  },
  {
    id: "C19",
    category: "C",
    name: "AI content detection (Ahrefs)",
    sopName: "AI content detection",
    action: "Review Content Quality",
    kind: "blocked",
    blockedReason: "Requires Ahrefs Site Audit AI-content signal",
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "C20",
    category: "C",
    name: "Page vs SERP title mismatch",
    sopName: "Page vs SERP title mismatch",
    action: "Improve Title Quality",
    kind: "blocked",
    blockedReason: "Requires GSC URL Inspection API + SERP title comparison",
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "C21",
    category: "C",
    name: "Meta description length bounds",
    sopName: "Meta description length bounds",
    action: "Fix Meta Description",
    kind: "blocked",
    blockedReason: "Not implemented. C15 and C16 carry the over-160 and under-100 halves; C21 adds the missing-tag and multiple-tag cases",
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "S1",
    category: "S",
    name: "Robots.txt",
    sopName: "Robots.txt",
    action: "Fix robots.txt",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "S2",
    category: "S",
    name: "Navigation (3-click reach, crawlable, mobile parity)",
    sopName: "Navigation",
    action: "Fix Navigation",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "S3",
    category: "S",
    name: "XML Sitemap",
    sopName: "XML Sitemap",
    action: "Fix Sitemap",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "S4",
    category: "S",
    name: "HTTPS enforcement",
    sopName: "HTTPS enforcement",
    action: "Fix HTTPS",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S5",
    category: "S",
    name: "Core Web Vitals",
    sopName: "Core Web Vitals",
    action: "Fix CWV (dev work)",
    kind: "blocked",
    blockedReason: "Requires PageSpeed / CWV integration",
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "S6",
    category: "S",
    name: "Schema sitewide",
    sopName: "Schema sitewide",
    action: "Fix Schema",
    kind: "blocked",
    blockedReason: "Requires SF structured data report",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S7",
    category: "S",
    name: "Duplicate content (SF reports)",
    sopName: "Duplicate content",
    action: "Resolve Duplicates",
    kind: "blocked",
    blockedReason: "Requires SF duplicate content report",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S8",
    category: "S",
    name: "Orphan pages",
    sopName: "Orphan pages",
    action: "Add Internal Links or Remove",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S9",
    category: "S",
    name: "Hreflang",
    sopName: "Hreflang",
    action: "Fix Hreflang (or N/A for single-language)",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P1",
  },
  {
    id: "S10",
    category: "S",
    name: "Social tags (OG/Twitter)",
    sopName: "Social tags (OG/Twitter)",
    action: "Add Social Tags",
    kind: "blocked",
    blockedReason: "Requires SF social-tags extract",
    kwDependency: "Fix Now",
    priority: "P3",
  },
  {
    id: "S11",
    category: "S",
    name: "Pagination",
    sopName: "Pagination",
    action: "Fix Pagination",
    kind: "active",
    blockedReason: null,
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S12",
    category: "S",
    name: "Platform Performance Ceiling",
    sopName: "Platform Performance Ceiling",
    action: "Document Ceiling / Flag Migration",
    kind: "blocked",
    blockedReason: "Requires platform-level perf analysis",
    kwDependency: "Fix Now",
    priority: "P2",
  },
  {
    id: "S13",
    category: "S",
    name: "SERP title fidelity",
    sopName: "SERP title fidelity",
    action: "Improve Title Quality",
    kind: "blocked",
    blockedReason: "Requires GSC URL Inspection API + SERP title comparison",
    kwDependency: "Fix Now, Revisit",
    priority: "P2",
  },
  {
    id: "S14",
    category: "S",
    name: "AI crawler access",
    sopName: "AI crawler access",
    action: "Fix AI Crawler Access",
    kind: "blocked",
    blockedReason: "Requires live user-agent requests against money URLs; robots.txt alone is not sufficient",
    kwDependency: "Fix Now",
    priority: "P1",
  },
];
