-- Per-page semantic embeddings, used by the WQA / pages section for
-- similarity ("find pages like this one"), keyword → page matching, and
-- content-gap detection. Generated by OpenAI text-embedding-3-small (1536
-- dimensions) on the page's BOILERPLATE-STRIPPED content — navigation,
-- header, and footer text is frequency-pruned before embedding so that
-- every page on a site doesn't look semantically identical.

create extension if not exists vector;

create table if not exists page_embedding (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid references property(id) on delete cascade,
  url           text not null,
  -- Embedding vector. 1536 dims matches text-embedding-3-small. Switch
  -- dimension if we change models.
  embedding     vector(1536) not null,
  -- The cleaned text we actually embedded (kept for debugging + future
  -- re-embedding if the cleaner changes).
  cleaned_text  text not null,
  -- Raw text we ingested, for traceability. Truncated to 50KB to keep row
  -- size sane.
  raw_text      text,
  -- SHA-256 of the cleaned_text — lets us skip re-embedding when the
  -- content hasn't changed.
  content_hash  text not null,
  model         text not null default 'text-embedding-3-small',
  source        text not null default 'sf:custom_javascript_page_content',
  -- Number of chars stripped as boilerplate (nav/footer/repeated lines).
  -- Useful for QA on the cleaner heuristics.
  stripped_chars integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- One embedding per (property, url). Re-running upserts in place.
create unique index if not exists idx_page_embedding_property_url
  on page_embedding (property_id, url);

-- HNSW index for cosine similarity. ivfflat would also work; HNSW is the
-- newer default and doesn't need a separate index-tuning step.
create index if not exists idx_page_embedding_hnsw
  on page_embedding using hnsw (embedding vector_cosine_ops);
